name: ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: write
      contents: write
    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: checkout
        uses: actions/checkout@v3

      - name: cache ~/.gradle/caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle.kts') }}

      - name: gradle clean build
        run: gradle clean build

      - name: gradle test
        run: gradle test

#      - name: bump and publish new version
#        run: sh ./scripts/publish.sh
